const FANTASMA = "fantasma";
const OJO = "Ojo";

const ENEMIGOS = [FANTASMA, OJO];

const ENEMIGOS_DELAY = {
  MIN: 1000,
  MAX: 2000,
};

const FUEGO = "fuego";
const VIDAEXTRA = "vidaExtra";

const OBSTACULOS = [FUEGO];
const OBSTACULOS_DELAY = 600;

const MONEDA = "moneda";
const CALIZ = "caliz";
const COLLAR = "collar";
const ESPEJO = "espejo";
const GEMA = "gema";

const OBJETOS = [MONEDA,VIDAEXTRA,CALIZ,COLLAR,ESPEJO,GEMA];
const OBJETOS_DELAY = 2000;

export {ENEMIGOS,ENEMIGOS_DELAY, FANTASMA, OJO,FUEGO,OBSTACULOS, OBSTACULOS_DELAY,MONEDA,CALIZ,COLLAR,ESPEJO,GEMA,OBJETOS,OBJETOS_DELAY,VIDAEXTRA};