const FANTASMA = "fantasma";
const OJO = "Ojo";

const FUEGO = "fuego"

const ENEMIGOS = [FANTASMA, OJO];

const OBSTACULOS = [FUEGO];

const ENEMIGOS_DELAY = 1800;

const OBSTACULOS_DELAY = 600;

export {ENEMIGOS,ENEMIGOS_DELAY, FANTASMA, OJO,FUEGO,OBSTACULOS, OBSTACULOS_DELAY};